package Entity;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Represents an analyzed report generated by the academic leader
 * with parameters: module, semester, lecturer
 */
public class AnalyzedReport {
    
    public enum ReportType {
        STUDENT_STATISTICS("Student Statistics"),
        GRADE_DISTRIBUTION("Grade Distribution"),
        MODULE_PERFORMANCE("Module Performance"),
        CLASS_COMPARISON("Class Comparison"),
        ASSESSMENT_ANALYSIS("Assessment Analysis");
        
        private final String displayName;
        
        ReportType(String displayName) {
            this.displayName = displayName;
        }
        
        public String getDisplayName() {
            return displayName;
        }
        
        public static ReportType fromString(String text) {
            for (ReportType type : ReportType.values()) {
                if (type.displayName.equalsIgnoreCase(text) || type.name().equalsIgnoreCase(text)) {
                    return type;
                }
            }
            return STUDENT_STATISTICS; // default
        }
    }
    
    private String reportId;
    private ReportType reportType;
    private String moduleCode;       // "ALL" if all modules selected
    private String semester;         // e.g., "2025-01", "2025-02", or "ALL"
    private String lecturerEmail;    // "ALL" if all lecturers selected
    private String generatedBy;      // Academic leader email who generated
    private String generatedDate;
    private String reportContent;    // The actual report data/summary
    private int totalRecords;        // Number of records in the report
    
    public AnalyzedReport(String reportId, ReportType reportType, String moduleCode, 
                          String semester, String lecturerEmail, String generatedBy) {
        this.reportId = reportId;
        this.reportType = reportType;
        this.moduleCode = moduleCode != null ? moduleCode : "ALL";
        this.semester = semester != null ? semester : "ALL";
        this.lecturerEmail = lecturerEmail != null ? lecturerEmail : "ALL";
        this.generatedBy = generatedBy;
        this.generatedDate = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
        this.reportContent = "";
        this.totalRecords = 0;
    }
    
    // Constructor for loading from file
    public AnalyzedReport(String reportId, String reportType, String moduleCode,
                          String semester, String lecturerEmail, String generatedBy,
                          String generatedDate, String reportContent, int totalRecords) {
        this.reportId = reportId;
        this.reportType = ReportType.fromString(reportType);
        this.moduleCode = moduleCode;
        this.semester = semester;
        this.lecturerEmail = lecturerEmail;
        this.generatedBy = generatedBy;
        this.generatedDate = generatedDate;
        this.reportContent = reportContent;
        this.totalRecords = totalRecords;
    }

    // Getters
    public String getReportId() { return reportId; }
    public ReportType getReportType() { return reportType; }
    public String getReportTypeString() { return reportType.getDisplayName(); }
    public String getModuleCode() { return moduleCode; }
    public String getSemester() { return semester; }
    public String getLecturerEmail() { return lecturerEmail; }
    public String getGeneratedBy() { return generatedBy; }
    public String getGeneratedDate() { return generatedDate; }
    public String getReportContent() { return reportContent; }
    public int getTotalRecords() { return totalRecords; }

    // Setters
    public void setReportId(String reportId) { this.reportId = reportId; }
    public void setReportType(ReportType reportType) { this.reportType = reportType; }
    public void setModuleCode(String moduleCode) { this.moduleCode = moduleCode; }
    public void setSemester(String semester) { this.semester = semester; }
    public void setLecturerEmail(String lecturerEmail) { this.lecturerEmail = lecturerEmail; }
    public void setGeneratedBy(String generatedBy) { this.generatedBy = generatedBy; }
    public void setGeneratedDate(String generatedDate) { this.generatedDate = generatedDate; }
    public void setReportContent(String reportContent) { this.reportContent = reportContent; }
    public void setTotalRecords(int totalRecords) { this.totalRecords = totalRecords; }
    
    /**
     * Format the report for display
     */
    public String getFormattedSummary() {
        StringBuilder sb = new StringBuilder();
        sb.append("Report ID: ").append(reportId).append("\n");
        sb.append("Type: ").append(reportType.getDisplayName()).append("\n");
        sb.append("Module: ").append(moduleCode).append("\n");
        sb.append("Semester: ").append(semester).append("\n");
        sb.append("Lecturer: ").append(lecturerEmail).append("\n");
        sb.append("Generated By: ").append(generatedBy).append("\n");
        sb.append("Generated Date: ").append(generatedDate).append("\n");
        sb.append("Total Records: ").append(totalRecords).append("\n");
        return sb.toString();
    }
    
    /**
     * Convert to file format for saving
     */
    public String toFileFormat() {
        // Use | as delimiter, escape any | in content
        String escapedContent = reportContent.replace("|", "{{PIPE}}").replace("\n", "{{NEWLINE}}");
        return String.join("|",
            reportId,
            reportType.name(),
            moduleCode,
            semester,
            lecturerEmail,
            generatedBy,
            generatedDate,
            escapedContent,
            String.valueOf(totalRecords)
        );
    }
    
    /**
     * Parse from file format
     */
    public static AnalyzedReport fromFileFormat(String line) {
        String[] parts = line.split("\\|", -1);
        if (parts.length < 9) return null;
        
        String content = parts[7].replace("{{PIPE}}", "|").replace("{{NEWLINE}}", "\n");
        int records = 0;
        try {
            records = Integer.parseInt(parts[8].trim());
        } catch (NumberFormatException e) {}
        
        return new AnalyzedReport(
            parts[0].trim(),  // reportId
            parts[1].trim(),  // reportType
            parts[2].trim(),  // moduleCode
            parts[3].trim(),  // semester
            parts[4].trim(),  // lecturerEmail
            parts[5].trim(),  // generatedBy
            parts[6].trim(),  // generatedDate
            content,          // reportContent
            records           // totalRecords
        );
    }
}
