package IOManage;

import Entity.AnalyzedReport;
import Entity.AnalyzedReport.ReportType;
import Entity.Module;
import Entity.ClassGroup;
import Users.User;

import java.io.*;
import java.util.ArrayList;
import java.util.Map;
import java.util.LinkedHashMap;

/**
 * Manager for handling analyzed reports - saving and loading from analyzedreport.txt
 */
public class AnalyzedReportManager {
    
    public static ArrayList<AnalyzedReport> analyzedReports = new ArrayList<>();
    private static final String FILE_PATH = "data/analyzedreport.txt";
    
    /**
     * Load all analyzed reports from file
     */
    public static void loadFromFile() {
        analyzedReports.clear();
        File file = new File(FILE_PATH);
        
        if (!file.exists()) {
            return;
        }
        
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.trim().isEmpty()) continue;
                AnalyzedReport report = AnalyzedReport.fromFileFormat(line);
                if (report != null) {
                    analyzedReports.add(report);
                }
            }
        } catch (IOException e) {
            System.out.println("Error loading analyzed reports: " + e.getMessage());
        }
    }
    
    /**
     * Save all analyzed reports to file
     */
    public static void saveToFile() {
        File dataDir = new File("data");
        if (!dataDir.exists()) {
            dataDir.mkdirs();
        }
        
        try (PrintWriter pw = new PrintWriter(new FileWriter(FILE_PATH))) {
            for (AnalyzedReport report : analyzedReports) {
                pw.println(report.toFileFormat());
            }
        } catch (IOException e) {
            System.out.println("Error saving analyzed reports: " + e.getMessage());
        }
    }
    
    /**
     * Add a new analyzed report
     */
    public static void addReport(AnalyzedReport report) {
        loadFromFile();
        analyzedReports.add(report);
        saveToFile();
    }
    
    /**
     * Get next report ID
     */
    public static String getNextReportId() {
        loadFromFile();
        int max = 0;
        for (AnalyzedReport r : analyzedReports) {
            try {
                String idNum = r.getReportId().replaceAll("[^0-9]", "");
                int num = Integer.parseInt(idNum);
                if (num > max) max = num;
            } catch (NumberFormatException e) {}
        }
        return "AR" + String.format("%03d", max + 1);
    }
    
    /**
     * Delete a report by ID
     */
    public static boolean deleteReport(String reportId) {
        loadFromFile();
        boolean removed = analyzedReports.removeIf(r -> r.getReportId().equalsIgnoreCase(reportId));
        if (removed) {
            saveToFile();
        }
        return removed;
    }
    
    /**
     * Find report by ID
     */
    public static AnalyzedReport findById(String reportId) {
        loadFromFile();
        for (AnalyzedReport r : analyzedReports) {
            if (r.getReportId().equalsIgnoreCase(reportId)) {
                return r;
            }
        }
        return null;
    }
    
    /**
     * Get all reports generated by a specific leader
     */
    public static ArrayList<AnalyzedReport> getReportsByLeader(String leaderEmail) {
        loadFromFile();
        ArrayList<AnalyzedReport> result = new ArrayList<>();
        for (AnalyzedReport r : analyzedReports) {
            if (r.getGeneratedBy().equalsIgnoreCase(leaderEmail)) {
                result.add(r);
            }
        }
        return result;
    }
    
    /**
     * Generate Student Statistics report
     */
    public static AnalyzedReport generateStudentStatisticsReport(String moduleCode, String semester, 
                                                                   String lecturerEmail, String generatedBy) {
        ModuleManager.loadAllModules();
        ClassManager.loadFromFile();
        UserManager.loadFromFile();
        
        String reportId = getNextReportId();
        AnalyzedReport report = new AnalyzedReport(reportId, ReportType.STUDENT_STATISTICS,
                                                    moduleCode, semester, lecturerEmail, generatedBy);
        
        StringBuilder content = new StringBuilder();
        Map<String, Integer> studentsPerModule = new LinkedHashMap<>();
        Map<String, Integer> studentsPerClass = new LinkedHashMap<>();
        int totalStudents = 0;
        int recordCount = 0;
        
        for (Module m : ModuleManager.modules) {
            // Filter by module
            if (!"ALL".equals(moduleCode) && !m.getCode().equalsIgnoreCase(moduleCode)) continue;
            
            // Filter by lecturer
            if (!"ALL".equals(lecturerEmail)) {
                boolean hasLecturer = false;
                for (ClassGroup cg : ClassManager.classGroups) {
                    if (cg.getModule() != null && cg.getModule().getCode().equalsIgnoreCase(m.getCode())) {
                        if (cg.getLecturerEmails().contains(lecturerEmail)) {
                            hasLecturer = true;
                            break;
                        }
                    }
                }
                if (!hasLecturer) continue;
            }
            
            int moduleStudentCount = 0;
            for (ClassGroup cg : ClassManager.classGroups) {
                if (cg.getModule() != null && cg.getModule().getCode().equalsIgnoreCase(m.getCode())) {
                    // Filter by lecturer for class
                    if (!"ALL".equals(lecturerEmail) && !cg.getLecturerEmails().contains(lecturerEmail)) continue;
                    
                    int classCount = cg.getStudentEmails().size();
                    studentsPerClass.put(cg.getClassCode() + " (" + m.getCode() + ")", classCount);
                    moduleStudentCount += classCount;
                    recordCount++;
                }
            }
            
            if (moduleStudentCount > 0) {
                studentsPerModule.put(m.getCode() + " - " + m.getName(), moduleStudentCount);
                totalStudents += moduleStudentCount;
            }
        }
        
        // Build content
        content.append("=== STUDENT STATISTICS REPORT ===\n\n");
        content.append("Parameters:\n");
        content.append("  Module: ").append(moduleCode).append("\n");
        content.append("  Semester: ").append(semester).append("\n");
        content.append("  Lecturer: ").append(lecturerEmail).append("\n\n");
        
        content.append("Summary:\n");
        content.append("  Total Students: ").append(totalStudents).append("\n");
        content.append("  Total Modules: ").append(studentsPerModule.size()).append("\n");
        content.append("  Total Classes: ").append(studentsPerClass.size()).append("\n\n");
        
        content.append("Students per Module:\n");
        for (Map.Entry<String, Integer> entry : studentsPerModule.entrySet()) {
            content.append("  ").append(entry.getKey()).append(": ").append(entry.getValue()).append("\n");
        }
        
        content.append("\nStudents per Class:\n");
        for (Map.Entry<String, Integer> entry : studentsPerClass.entrySet()) {
            content.append("  ").append(entry.getKey()).append(": ").append(entry.getValue()).append("\n");
        }
        
        report.setReportContent(content.toString());
        report.setTotalRecords(recordCount);
        
        return report;
    }
    
    /**
     * Generate Grade Distribution report
     */
    public static AnalyzedReport generateGradeDistributionReport(String moduleCode, String semester,
                                                                   String lecturerEmail, String generatedBy) {
        ModuleManager.loadAllModules();
        ClassManager.loadFromFile();
        UserManager.loadFromFile();
        GradingSystemManager.loadFromFile();
        
        String reportId = getNextReportId();
        AnalyzedReport report = new AnalyzedReport(reportId, ReportType.GRADE_DISTRIBUTION,
                                                    moduleCode, semester, lecturerEmail, generatedBy);
        
        StringBuilder content = new StringBuilder();
        Map<String, Integer> gradeDistribution = new LinkedHashMap<>();
        gradeDistribution.put("A+", 0); gradeDistribution.put("A", 0); gradeDistribution.put("A-", 0);
        gradeDistribution.put("B+", 0); gradeDistribution.put("B", 0); gradeDistribution.put("B-", 0);
        gradeDistribution.put("C+", 0); gradeDistribution.put("C", 0); gradeDistribution.put("C-", 0);
        gradeDistribution.put("D", 0); gradeDistribution.put("F", 0);
        
        int totalRecords = 0;
        
        // Load marks data
        File marksFile = new File("data/marks.txt");
        if (marksFile.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(marksFile))) {
                String line;
                while ((line = br.readLine()) != null) {
                    if (line.trim().isEmpty()) continue;
                    String[] parts = line.split("\\|");
                    if (parts.length >= 7) {
                        String markModuleCode = parts[1].trim();
                        String markLecturerEmail = parts[2].trim();
                        double marks = Double.parseDouble(parts[6].trim());
                        
                        // Apply filters
                        if (!"ALL".equals(moduleCode) && !markModuleCode.equalsIgnoreCase(moduleCode)) continue;
                        if (!"ALL".equals(lecturerEmail) && !markLecturerEmail.equalsIgnoreCase(lecturerEmail)) continue;
                        
                        // Get grade based on percentage (assuming max 100)
                        double percentage = marks; // Assuming marks are already percentages
                        String grade = getGradeFromPercentage(percentage);
                        
                        gradeDistribution.merge(grade, 1, Integer::sum);
                        totalRecords++;
                    }
                }
            } catch (IOException | NumberFormatException e) {}
        }
        
        // Build content
        content.append("=== GRADE DISTRIBUTION REPORT ===\n\n");
        content.append("Parameters:\n");
        content.append("  Module: ").append(moduleCode).append("\n");
        content.append("  Semester: ").append(semester).append("\n");
        content.append("  Lecturer: ").append(lecturerEmail).append("\n\n");
        
        content.append("Grade Distribution:\n");
        for (Map.Entry<String, Integer> entry : gradeDistribution.entrySet()) {
            content.append("  ").append(entry.getKey()).append(": ").append(entry.getValue()).append("\n");
        }
        content.append("\nTotal Marks Analyzed: ").append(totalRecords).append("\n");
        
        report.setReportContent(content.toString());
        report.setTotalRecords(totalRecords);
        
        return report;
    }
    
    /**
     * Generate Module Performance report
     */
    public static AnalyzedReport generateModulePerformanceReport(String moduleCode, String semester,
                                                                   String lecturerEmail, String generatedBy) {
        ModuleManager.loadAllModules();
        ClassManager.loadFromFile();
        
        String reportId = getNextReportId();
        AnalyzedReport report = new AnalyzedReport(reportId, ReportType.MODULE_PERFORMANCE,
                                                    moduleCode, semester, lecturerEmail, generatedBy);
        
        StringBuilder content = new StringBuilder();
        Map<String, Double> moduleAverages = new LinkedHashMap<>();
        Map<String, Integer> moduleStudentCounts = new LinkedHashMap<>();
        int totalRecords = 0;
        
        // Load marks and calculate averages per module
        Map<String, Double> moduleTotalMarks = new LinkedHashMap<>();
        Map<String, Integer> moduleMarkCounts = new LinkedHashMap<>();
        
        File marksFile = new File("data/marks.txt");
        if (marksFile.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(marksFile))) {
                String line;
                while ((line = br.readLine()) != null) {
                    if (line.trim().isEmpty()) continue;
                    String[] parts = line.split("\\|");
                    if (parts.length >= 7) {
                        String markModuleCode = parts[1].trim();
                        String markLecturerEmail = parts[2].trim();
                        double marks = Double.parseDouble(parts[6].trim());
                        
                        // Apply filters
                        if (!"ALL".equals(moduleCode) && !markModuleCode.equalsIgnoreCase(moduleCode)) continue;
                        if (!"ALL".equals(lecturerEmail) && !markLecturerEmail.equalsIgnoreCase(lecturerEmail)) continue;
                        
                        moduleTotalMarks.merge(markModuleCode, marks, Double::sum);
                        moduleMarkCounts.merge(markModuleCode, 1, Integer::sum);
                        totalRecords++;
                    }
                }
            } catch (IOException | NumberFormatException e) {}
        }
        
        // Calculate averages
        for (String mod : moduleTotalMarks.keySet()) {
            double avg = moduleTotalMarks.get(mod) / moduleMarkCounts.get(mod);
            moduleAverages.put(mod, avg);
        }
        
        // Build content
        content.append("=== MODULE PERFORMANCE REPORT ===\n\n");
        content.append("Parameters:\n");
        content.append("  Module: ").append(moduleCode).append("\n");
        content.append("  Semester: ").append(semester).append("\n");
        content.append("  Lecturer: ").append(lecturerEmail).append("\n\n");
        
        content.append("Module Performance (Average Marks):\n");
        for (Map.Entry<String, Double> entry : moduleAverages.entrySet()) {
            content.append("  ").append(entry.getKey()).append(": ")
                   .append(String.format("%.2f", entry.getValue())).append("%\n");
        }
        content.append("\nTotal Marks Analyzed: ").append(totalRecords).append("\n");
        
        report.setReportContent(content.toString());
        report.setTotalRecords(totalRecords);
        
        return report;
    }
    
    /**
     * Generate Class Comparison report
     */
    public static AnalyzedReport generateClassComparisonReport(String moduleCode, String semester,
                                                                 String lecturerEmail, String generatedBy) {
        ModuleManager.loadAllModules();
        ClassManager.loadFromFile();
        
        String reportId = getNextReportId();
        AnalyzedReport report = new AnalyzedReport(reportId, ReportType.CLASS_COMPARISON,
                                                    moduleCode, semester, lecturerEmail, generatedBy);
        
        StringBuilder content = new StringBuilder();
        Map<String, Double> classAverages = new LinkedHashMap<>();
        int totalRecords = 0;
        
        // Load marks and calculate averages per class
        Map<String, Double> classTotalMarks = new LinkedHashMap<>();
        Map<String, Integer> classMarkCounts = new LinkedHashMap<>();
        
        // First, build class code to module mapping from ClassManager
        Map<String, String> classToModule = new LinkedHashMap<>();
        for (ClassGroup cg : ClassManager.classGroups) {
            if (cg.getModule() != null) {
                classToModule.put(cg.getClassCode(), cg.getModule().getCode());
            }
        }
        
        File marksFile = new File("data/marks.txt");
        if (marksFile.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(marksFile))) {
                String line;
                while ((line = br.readLine()) != null) {
                    if (line.trim().isEmpty()) continue;
                    String[] parts = line.split("\\|");
                    if (parts.length >= 7) {
                        String markModuleCode = parts[1].trim();
                        String markLecturerEmail = parts[2].trim();
                        double marks = Double.parseDouble(parts[6].trim());
                        
                        // Apply filters
                        if (!"ALL".equals(moduleCode) && !markModuleCode.equalsIgnoreCase(moduleCode)) continue;
                        if (!"ALL".equals(lecturerEmail) && !markLecturerEmail.equalsIgnoreCase(lecturerEmail)) continue;
                        
                        // Group by class - find class from module
                        for (ClassGroup cg : ClassManager.classGroups) {
                            if (cg.getModule() != null && cg.getModule().getCode().equalsIgnoreCase(markModuleCode)) {
                                String classKey = cg.getClassCode() + " (" + markModuleCode + ")";
                                classTotalMarks.merge(classKey, marks, Double::sum);
                                classMarkCounts.merge(classKey, 1, Integer::sum);
                                totalRecords++;
                                break;
                            }
                        }
                    }
                }
            } catch (IOException | NumberFormatException e) {}
        }
        
        // Calculate averages
        for (String cls : classTotalMarks.keySet()) {
            double avg = classTotalMarks.get(cls) / classMarkCounts.get(cls);
            classAverages.put(cls, avg);
        }
        
        // Build content
        content.append("=== CLASS COMPARISON REPORT ===\n\n");
        content.append("Parameters:\n");
        content.append("  Module: ").append(moduleCode).append("\n");
        content.append("  Semester: ").append(semester).append("\n");
        content.append("  Lecturer: ").append(lecturerEmail).append("\n\n");
        
        content.append("Class Performance (Average Marks):\n");
        for (Map.Entry<String, Double> entry : classAverages.entrySet()) {
            content.append("  ").append(entry.getKey()).append(": ")
                   .append(String.format("%.2f", entry.getValue())).append("%\n");
        }
        content.append("\nTotal Marks Analyzed: ").append(totalRecords).append("\n");
        
        report.setReportContent(content.toString());
        report.setTotalRecords(totalRecords);
        
        return report;
    }
    
    /**
     * Generate Assessment Analysis report
     */
    public static AnalyzedReport generateAssessmentAnalysisReport(String moduleCode, String semester,
                                                                    String lecturerEmail, String generatedBy) {
        ModuleManager.loadAllModules();
        
        String reportId = getNextReportId();
        AnalyzedReport report = new AnalyzedReport(reportId, ReportType.ASSESSMENT_ANALYSIS,
                                                    moduleCode, semester, lecturerEmail, generatedBy);
        
        StringBuilder content = new StringBuilder();
        Map<String, Map<String, Object>> assessmentStats = new LinkedHashMap<>();
        int totalRecords = 0;
        
        // Load assessments and marks
        Map<String, String[]> assessments = new LinkedHashMap<>();
        File assessFile = new File("data/assessments.txt");
        if (assessFile.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(assessFile))) {
                String line;
                while ((line = br.readLine()) != null) {
                    if (line.trim().isEmpty()) continue;
                    String[] parts = line.split("\\|");
                    if (parts.length >= 6) {
                        String assessId = parts[0].trim();
                        String assessModuleCode = parts[1].trim();
                        String assessLecturerEmail = parts[2].trim();
                        String assessName = parts[3].trim();
                        String assessType = parts[4].trim();
                        
                        // Apply filters
                        if (!"ALL".equals(moduleCode) && !assessModuleCode.equalsIgnoreCase(moduleCode)) continue;
                        if (!"ALL".equals(lecturerEmail) && !assessLecturerEmail.equalsIgnoreCase(lecturerEmail)) continue;
                        
                        assessments.put(assessId, new String[]{assessModuleCode, assessName, assessType});
                    }
                }
            } catch (IOException e) {}
        }
        
        // Calculate stats per assessment
        File marksFile = new File("data/marks.txt");
        if (marksFile.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(marksFile))) {
                String line;
                while ((line = br.readLine()) != null) {
                    if (line.trim().isEmpty()) continue;
                    String[] parts = line.split("\\|");
                    if (parts.length >= 7) {
                        String assessId = parts[0].trim();
                        double marks = Double.parseDouble(parts[6].trim());
                        
                        if (assessments.containsKey(assessId)) {
                            if (!assessmentStats.containsKey(assessId)) {
                                Map<String, Object> stats = new LinkedHashMap<>();
                                stats.put("name", assessments.get(assessId)[1]);
                                stats.put("type", assessments.get(assessId)[2]);
                                stats.put("module", assessments.get(assessId)[0]);
                                stats.put("total", 0.0);
                                stats.put("count", 0);
                                stats.put("min", Double.MAX_VALUE);
                                stats.put("max", Double.MIN_VALUE);
                                assessmentStats.put(assessId, stats);
                            }
                            
                            Map<String, Object> stats = assessmentStats.get(assessId);
                            stats.put("total", (Double) stats.get("total") + marks);
                            stats.put("count", (Integer) stats.get("count") + 1);
                            if (marks < (Double) stats.get("min")) stats.put("min", marks);
                            if (marks > (Double) stats.get("max")) stats.put("max", marks);
                            totalRecords++;
                        }
                    }
                }
            } catch (IOException | NumberFormatException e) {}
        }
        
        // Build content
        content.append("=== ASSESSMENT ANALYSIS REPORT ===\n\n");
        content.append("Parameters:\n");
        content.append("  Module: ").append(moduleCode).append("\n");
        content.append("  Semester: ").append(semester).append("\n");
        content.append("  Lecturer: ").append(lecturerEmail).append("\n\n");
        
        content.append("Assessment Statistics:\n");
        for (Map.Entry<String, Map<String, Object>> entry : assessmentStats.entrySet()) {
            Map<String, Object> stats = entry.getValue();
            int count = (Integer) stats.get("count");
            double avg = count > 0 ? (Double) stats.get("total") / count : 0;
            double min = count > 0 ? (Double) stats.get("min") : 0;
            double max = count > 0 ? (Double) stats.get("max") : 0;
            
            content.append("\n  ").append(entry.getKey()).append(" - ").append(stats.get("name")).append("\n");
            content.append("    Type: ").append(stats.get("type")).append("\n");
            content.append("    Module: ").append(stats.get("module")).append("\n");
            content.append("    Submissions: ").append(count).append("\n");
            content.append("    Average: ").append(String.format("%.2f", avg)).append("\n");
            content.append("    Min: ").append(String.format("%.2f", min)).append("\n");
            content.append("    Max: ").append(String.format("%.2f", max)).append("\n");
        }
        content.append("\nTotal Marks Analyzed: ").append(totalRecords).append("\n");
        
        report.setReportContent(content.toString());
        report.setTotalRecords(totalRecords);
        
        return report;
    }
    
    /**
     * Helper method to get grade from percentage
     */
    private static String getGradeFromPercentage(double percentage) {
        if (percentage >= 90) return "A+";
        if (percentage >= 80) return "A";
        if (percentage >= 75) return "A-";
        if (percentage >= 70) return "B+";
        if (percentage >= 65) return "B";
        if (percentage >= 60) return "B-";
        if (percentage >= 55) return "C+";
        if (percentage >= 50) return "C";
        if (percentage >= 45) return "C-";
        if (percentage >= 40) return "D";
        return "F";
    }
}
